In [3]:
import pandas as pd

datas = []
for i in range(30):
    data = i*2
    datas.append(data)

# print(datas)

df = pd.DataFrame(datas,columns=['reward'])

print(df)


    reward
0        0
1        2
2        4
3        6
4        8
5       10
6       12
7       14
8       16
9       18
10      20
11      22
12      24
13      26
14      28
15      30
16      32
17      34
18      36
19      38
20      40
21      42
22      44
23      46
24      48
25      50
26      52
27      54
28      56
29      58


In [4]:
from sionna_sensing.config.config_load import config_load

_,_ = config_load('./sionna_sensing/config/config test.json')

In [6]:
from tensorflow.python.keras.optimizer_v2.adam import Adam
from tensorflow.python.keras.optimizer_v2.rmsprop import RMSprop
Adam(lr=0.01, clipnorm=1.)
RMSprop(lr=0.01)

In [20]:
import numpy as np
target_num = 3
c = np.array([[ 0.739, 0.789, 0.786, 0.836, 0.782, 0.749, 0.752],
              [-0.148,-0.263,-0.061, 1.   ,-1.   , 0.283,-1.   ],
              [ 0.545,-1.   ,-0.291,-1.   ,-0.055,-1.   ,-0.09 ]])
actions = np.array([1, 0, -1, 0, 2, 0, 1])
reward = 0
for idx in range(target_num):
    mask = np.where(actions==idx, 1, 0)
    tmp = c[idx,:] * mask
    print(mask)
    print(tmp)
    print(np.max(tmp))
    reward += np.max(tmp)
reward /= target_num
print(f'reward:{reward}')


[0 1 0 1 0 1 0]
[0.    0.789 0.    0.836 0.    0.749 0.   ]
0.836
[1 0 0 0 0 0 1]
[-0.148 -0.    -0.     0.    -0.     0.    -1.   ]
0.0
[0 0 0 0 1 0 0]
[ 0.    -0.    -0.    -0.    -0.055 -0.    -0.   ]
-0.0
reward:0.2786666666666667
